# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 15:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20171220_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 20, 15, 21, 18, 661469, tzinfo=utc)),
        ),
    ]
