# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 16:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20171220_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.TextField(default=None, max_length=20, null=True)),
                ('quiz_id', models.CharField(max_length=100)),
                ('attempted_date', models.DateField(default=datetime.datetime(2017, 12, 20, 16, 49, 41, 937488, tzinfo=utc))),
                ('marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('student_response', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 20, 16, 49, 41, 937488, tzinfo=utc)),
        ),
    ]
