# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-24 10:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20171220_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresponse',
            name='attempted_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 24, 10, 3, 32, 601123, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='students',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 24, 10, 3, 32, 601123, tzinfo=utc)),
        ),
    ]
