# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 18:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20171224_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='time_remaining',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='attempted_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 27, 18, 0, 26, 95467, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='students',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 27, 18, 0, 26, 94465, tzinfo=utc)),
        ),
    ]
