# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 18:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(max_length=100)),
                ('cat', models.CharField(default='GK', max_length=100)),
                ('crt_dt', models.DateField(default=datetime.datetime(2017, 10, 18, 18, 44, 38, 831439, tzinfo=utc))),
                ('exp_dt', models.DateField(default=datetime.datetime(2017, 10, 25, 18, 44, 38, 831439, tzinfo=utc))),
                ('auth', models.CharField(max_length=100)),
                ('questions', models.TextField()),
            ],
        ),
    ]
