# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 15:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_page', '0008_auto_20171103_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='result_hold',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='crt_dt',
            field=models.DateField(default=datetime.datetime(2017, 12, 20, 15, 18, 15, 862648, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='exp_dt',
            field=models.DateField(default=datetime.datetime(2017, 12, 27, 15, 18, 15, 862648, tzinfo=utc)),
        ),
    ]
