# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 18:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_page', '0015_auto_20171224_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='crt_dt',
            field=models.DateField(default=datetime.datetime(2017, 12, 27, 18, 0, 26, 90352, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='exp_dt',
            field=models.DateField(default=datetime.datetime(2018, 1, 3, 18, 0, 26, 90352, tzinfo=utc)),
        ),
    ]
