# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_page', '0016_auto_20171227_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='crt_dt',
            field=models.DateField(default=datetime.datetime(2018, 1, 1, 15, 41, 32, 63683, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='exp_dt',
            field=models.DateField(default=datetime.datetime(2018, 1, 8, 15, 41, 32, 63683, tzinfo=utc)),
        ),
    ]
