# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_page', '0018_auto_20180101_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='crt_dt',
            field=models.DateField(default=datetime.datetime(2018, 1, 24, 17, 33, 5, 777075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='exp_dt',
            field=models.DateField(default=datetime.datetime(2018, 1, 31, 17, 33, 5, 777075, tzinfo=utc)),
        ),
    ]
